variable "root_domain" {}
variable "ssh_key_fingerprint" {}
variable "os_image" {}
variable "region" {}
variable "size" {}
variable "enable_ipv6" {}
variable "enable_backups" {}
variable "enable_monitoring" {}
variable "node_count" {}
